sudo: false
language: go
go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
install:
  - # Skip.
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d .)
  - go tool vet .
  - go test -v -race ./...
